### ISSUE TITLE
[Bug?] Lack of Config file?

### ISSUE THREAD

**Issue by BioTechproject27** [bytzo/sessility#6]
There does not seem to be a config file generated when the mod is installed and the game launched.
Used sessility-0.3 in 1.20.1

And if we need to simply make one ourselves, how does it have to be named? Does it need to be a .txt, .json, .conf, something else?
I'm very confused.

**Comment by bytzo** [comment]
Hi there! The config file should be titled `sessility.properties` and should be located in Fabric Loader's `config` folder (by default it is in the working directory of the server). Do you see sessility listed in your server's `latest.log` log file? Perhaps the mod is not loading for some reason.

**Comment by BioTechproject27** [comment]
Hmm, it is in fact not loading the mod according to my log (I just skipped over it the first time, as I didn't see any errors), are there any dependencies?

**Comment by bytzo** [comment]
Would you be able to send the `latest.log` file here? I'll try to take a look at it and see what the problem may be.

**Comment by BioTechproject27** [comment]
It is currently only on a minecraft profile, not a dedicated server, could that somehow influence the startup?

**Comment by BioTechproject27** [comment]
[latest.log](https://github.com/bytzo/sessility/files/13551607/latest.log)

**Comment by bytzo** [comment]
Yeah, unfortunately Sessility is a server-only mod, so it would not work for your use case. You'll likely need to look for an alternative mod that offers client-side functionality. It looks like the mod [AfkPlus](https://modrinth.com/mod/afkplus) might be able to run on the client, although I have not tested it myself.

**Comment by BioTechproject27** [comment]
Ah, I'm just testing and configuring mods (beforehand) for a future (external, dedicated) server that I'd play on with friends.
I'll report back if I encounter any issues with sessility when setting up the server. Thank you for now!
